### PR TITLE
Made prompt_toolkit's mouse_support optional

### PR DESCRIPTION
**Pull request by mdraw**
Introducing a new environment variable MOUSE_SUPPORT for this,
which can either be True or False. Default is False.

TODO: The documentation in docs/envvars.rst should be extended.

This is meant for https://github.com/scopatz/xonsh/pull/393

### CODE REVIEW

**Comment by jonathanslenders** [comment]
To me, this looks good. I'll merge it.

edit: Actually, should I merge this in this branch? Or do you merge my branch in Xonsh/master and than merge that, or do you want me to squanch that commit into the commit of this branch?

**Comment by mdraw** [comment]
I am not sure how such situations are usually handled, but yes, I thought you would merge my pull request into your new-features branch (should be as easy as clicking one button in the Github UI). As far as I understand, this will automatically add my commit to your PR https://github.com/scopatz/xonsh/pull/393.
Thanks!

**Comment by mdraw** [comment]
As I stated in the commit message, I think the documentation on mouse support should be extended. I don't quite understand how your mouse support code works, @jonathanslenders, so I thought it would be best if **you** could please add some information about this feature to the xonsh docs after merging my branch. Most importantly, the effect on terminal scrolling and clicking should be somehow noted so no new bug reports like mine here (https://github.com/jonathanslenders/python-prompt-toolkit/issues/168) will be created by other users.

**Comment by scopatz** [comment]
You can probably just merge it here @jonathanslenders

**Comment by mdraw** [comment]
Closing this because it has been merged upstream in https://github.com/scopatz/xonsh/commit/3961310418a922e1eb4c14a7a9e49247f061bf82.

**Pull request closed without merging**
